team:
  orange:
    name: "DEFENSEUR"
    color: "GOLD"
    data: 1
  white:
    name: "GRIS"
    color: "GRAY"
    data: 7
  lightblue:
    name: "BLUE"
    color: "BLUE"
    data: 11
  yellow:
    name: "YELLOW"
    color: "YELLOW"
    data: 4
  pink:
    name: "ROSE"
    color: "LIGHT_PURPLE"
    data: 6
  purple:
    name: "VIOLET"
    color: "DARK_PURPLE"
    data: 10
  aqua:
    name: "AQUA"
    color: "AQUA"
    data: 9
  green:
    name: "VERT"
    color: "GREEN"
    data: 13
  red:
    name: "RED"
    color: "RED"
    data: 14